#pragma once

#define ETH_ALEN 6

enum batadv_rlnc_io {
    PLAIN_PACKET = 0,
    ENC_PACKET,
    RED_PACKET,
    DEC_PACKET,
    REC_PACKET,
    HLP_PACKET,
    REQ_PACKET,
    ACK_PACKET,
    PACKET_NUM,
};

enum {
    BATADV_HLP_A_UNSPEC,
    BATADV_HLP_A_IFNAME,
    BATADV_HLP_A_IFINDEX,
    BATADV_HLP_A_SRC,
    BATADV_HLP_A_DST,
    BATADV_HLP_A_ADDR,
    BATADV_HLP_A_TQ,
    BATADV_HLP_A_HOP_LIST,
    BATADV_HLP_A_RLY_LIST,
    BATADV_HLP_A_FRAME,
    BATADV_HLP_A_BLOCK,
    BATADV_HLP_A_INT,
    BATADV_HLP_A_TYPE,
    BATADV_HLP_A_RANK,
    BATADV_HLP_A_SEQ,
    BATADV_HLP_A_ENCS,
    BATADV_HLP_A_E1,
    BATADV_HLP_A_E2,
    BATADV_HLP_A_E3,
    BATADV_HLP_A_NUM,
};
#define BATADV_HLP_A_MAX (BATADV_HLP_A_NUM - 1)

enum {
    BATADV_HLP_HOP_A_UNSPEC,
    BATADV_HLP_HOP_A_INFO,
    BATADV_HLP_HOP_A_NUM,
};
#define BATADV_HLP_HOP_A_MAX (BATADV_HLP_HOP_A_NUM - 1)

enum {
    BATADV_HLP_RLY_A_UNSPEC,
    BATADV_HLP_RLY_A_INFO,
    BATADV_HLP_RLY_A_NUM,
};
#define BATADV_HLP_RLY_A_MAX (BATADV_HLP_RLY_A_NUM - 1)

enum {
    BATADV_HLP_C_UNSPEC,
    BATADV_HLP_C_REGISTER,
    BATADV_HLP_C_GET_RELAYS,
    BATADV_HLP_C_GET_LINK,
    BATADV_HLP_C_GET_ONE_HOP,
    BATADV_HLP_C_FRAME,
    BATADV_HLP_C_BLOCK,
    BATADV_HLP_C_UNBLOCK,
    BATADV_HLP_C_NUM,
};
#define BATADV_HLP_C_MAX (BATADV_HLP_C_NUM - 1)
