#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.objects(
            source='io.cpp',
            target='io',
            includes=['/usr/include/libnl3'],
            export_includes=['/usr/include/libnl3'],
            use=['gflags', 'glog', 'nl-3', 'nl-genl-3', 'encoder', 'decoder']
    )

    bld.objects(
            source=['encoder_map.cpp', 'encoder.cpp'],
            target='encoder',
            includes=['/usr/include/libnl3'],
            use=['kodo', 'gflags', 'pthread'],
    )

    bld.objects(
            source=['decoder_map.cpp', 'decoder.cpp'],
            target='decoder',
            includes=['/usr/include/libnl3'],
            use=['kodo', 'gflags', 'pthread'],
    )

    bld(
            export_includes=[bld.env.BOOST],
            name='boost'
    )

    bld(
            use=['boost'],
            export_includes=[bld.env.KODO, bld.env.FIFI, bld.env.SAK],
            name='kodo'
    )

    bld(
            use=['io'],
            uselib=['gflags', 'glog'],
            name='libs'
    )

    src = bld.program(
            target='source',
            source='source.cpp',
            use=['libs', 'kodo', 'rt', 'pthread']
    )

    if hasattr(bld.env, 'PROFILER'):
        src.use.append('profiler')

    bld.program(
            target='counters',
            source='counters.cpp',
            use=['rt', 'pthread', 'boost'],
    )
